image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cifront:0.7.0

stages:
  - node_build
  - docker_build

node_build:
  image: registry.cn-hangzhou.aliyuncs.com/hzero-cli/cifront:0.0.1 # 正常打包
  # image: registry.hdsd.cn/operation-hdbsp-uat2/hdbsp-npm:1.0  # 离线打包
  stage: node_build
  script:
    - node_build
  only:
    - uat
    - tags
  except:
    - develop
    - /^feature-.*$/
    - /^release-.*$/
    - /^hotfix-.*$/

docker_build:
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cibase:0.7.0
  stage: docker_build
  script:
    - docker_build
  only:
    - uat
    - tags
  except:
    - develop
    - /^feature-.*$/
    - /^release-.*$/
    - /^hotfix-.*$/

.auto_devops: &auto_devops |
  http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=front"`
  if [ "$http_status_code" != "200" ]; then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh
  export TEMP_DIR=/cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-uni
  echo "gitlab-ci -- 缓存目录: $TEMP_DIR"


  function node_build(){
      echo "删除dist"
      rm -rf ./dist
      echo "==: 开始安装依赖"
      node -v
      yarn config set ignore-engines true
      yarn install
      echo "编译小程序"
      npm run build
      back_node_cache_and_build_cache
  }

  function back_node_cache_and_build_cache(){
      echo "===: 缓存文件"
      mkdir -p $TEMP_DIR
      tar -zcf $TEMP_DIR/dist.tar.gz ./dist
  }


  export GROUP_NAME=htc
  export DOCKER_USER=User6371438
  export DOCKER_PWD=User6371438PWD
  function docker_build(){
      # cp -r /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/* ${1:-"."}
      tar -zxf $TEMP_DIR/dist.tar.gz
      docker login -u ${DOCKER_USER} -p ${DOCKER_PWD} ${DOCKER_REGISTRY}
      docker build --pull -t ${DOCKER_REGISTRY}/${GROUP_NAME}/htc-uni:${CI_COMMIT_TAG} ${1:-"."}
      docker push ${DOCKER_REGISTRY}/${GROUP_NAME}/htc-uni:${CI_COMMIT_TAG}
      echo "镜像：${DOCKER_REGISTRY}/${GROUP_NAME}/htc-uni:${CI_COMMIT_TAG}"
  }

before_script:
  - *auto_devops
